---
- name: adding a virtual machine NIC to LoadBalancer
  hosts: localhost
  connection: local
  vars:
    vnet: /subscriptions/XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX/resourceGroups/network/providers/Microsoft.Network/virtualNetworks/vnet
    sbunet: mybackend
    resourcegroup: compute
    backend_address_pool: /subscriptions/XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX/resourceGroups/network/providers/Microsoft.Network/virtualNetworks/vnet
    ipconfiguration_name: ipconfig1
    publicip_nic: ACS-ip
    nic_vm: acs398
  tasks:
  - debug:
      msg: "deleting {{ nic_vm }} from LoadBalancer"
  - azure_rm_networkinterface:
      name: "{{ nic_vm }}"
      virtual_network: "{{ vnet }}"
      subnet_name: "{{ sbunet }}"
      resource_group: "{{ resourcegroup }}"
      ip_configurations:
        - name: "{{ ipconfiguration_name }}"
          public_ip_address_name: "{{ publicip_nic }}"
  - name: confirmation
    debug:
      msg: "deleted {{ nic_vm }} from LoadBalancer"
