- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: myResourceGroup
        name: myVM
        allocated: no